apiVersion: v1
kind: Service
metadata:
  name: fluent
  namespace: kube-logs
spec:
  type: LoadBalancer
  selector:
    app: fluent
  ports:
    - port: 24224
      targetPort: 24224
      name: fluent-forward
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-configmap
  namespace: kube-logs
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match app.logs*>
      @type elasticsearch
      host es-rest.kube-logs.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix app.logs
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent
  namespace: kube-logs
spec:
  selector:
    matchLabels:
      app: fluent
  replicas: 2
  template:
    metadata:
      labels:
        app: fluent
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: fluent
          image: breda/fluentd-elasticsearch:v1.14-debian-1
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 1000
          resources:
            limits:
              cpu: 1000m
              memory: 512M
            requests:
              cpu: 100m
              memory: 512M
          ports:
            - containerPort: 24224
          env:
            - name: FLUENTD_CONF
              value: "fluent.conf"
          volumeMounts:
            - name: fluent-config-volume
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
      volumes:
        - name: fluent-config-volume
          configMap:
            name: fluent-configmap