name: App Docker Image CI

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  BuildAndDeploy:
    env:
      DOCKERHUB_USERNAME: "breda"
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
    - name: Build the Docker image
      run: docker build ./app --file Dockerfile --tag $DOCKERHUB_USERNAME/do-kube-logger:latest
    - name: Push the Docker image
      run: docker push $DOCKERHUB_USERNAME/do-kube-logger:latest
